# Generated by Django 5.1.2 on 2024-10-25 20:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundoImobiliario',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('codigo', models.CharField(choices=[('hospital', 'Hospital'), ('hotel', 'Hotel'), ('hobrido', 'Híbrido'), ('lajes_corporativas', 'Lajes Corporativas'), ('logistica', 'Logística'), ('outros', 'Outros'), ('residencial', 'Residencial'), ('titulos_valores_mobiliarios', 'Titulos e val. Mob.')], max_length=30)),
                ('setor', models.CharField(choices=[('hospital', 'Hospital'), ('hotel', 'Hotel'), ('hobrido', 'Híbrido'), ('lajes_corporativas', 'Lajes Corporativas'), ('logistica', 'Logística'), ('outros', 'Outros'), ('residencial', 'Residencial'), ('titulos_valores_mobiliarios', 'Titulos e val. Mob.')], max_length=30)),
                ('dividend_yield_medio_12m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vacancia_financeira', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vacancia_fisica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade_ativos', models.IntegerField(default=0)),
            ],
        ),
    ]
